### ISSUE TITLE
FreeBSD virtual box created without longmode enabled.

### ISSUE THREAD

**Issue by Infiniverse** [ployground/ploy_virtualbox#7]
Using the ploy-quickstart, the Virtual box image isn't being created with 64 bit extensions enabled:

    <Hardware version="2">
      <CPU count="1" hotplug="false">
        <HardwareVirtEx enabled="true"/>
        <HardwareVirtExNestedPaging enabled="true"/>
        <HardwareVirtExVPID enabled="true"/>
        <HardwareVirtExUX enabled="true"/>
        <PAE enabled="true"/>
        <LongMode enabled="false"/>
        <HardwareVirtExLargePages enabled="true"/>
        <HardwareVirtForce enabled="false"/>
      </CPU>

LongMode is false, which prevents the mfsboot from booting the kernel. This is with the version of ploy from git, and the current version of virtualbox.

**Comment by Infiniverse** [comment]
Ok, I deleted the virtual box and ran it again, and now it's created with LongMode true; that seems strange. What governs this config?

**Comment by tomster** [comment]
this seems like a residual effect from having initially created the box with an older version of ploy_virtualbox (further strengthening my initial assumption on #6)

basically, the box was created without any of the defaults that bsdploy "injects" and thus it missed vital things like 64 bit mode (which what i guess is meant by LongMode...)

IOW the config is governed in part by defaults supplied by bsdploy but they weren't applied due to an outdated version of ploy_virtualbox,

**Comment by Infiniverse** [comment]
Great. All appears to be working now. Thanks for your help this morning :).
